name: msthesis
channels:
  - conda-forge
dependencies:
  # required
  - python=3.9.1
  - pip==20.3.3

  - boto3
  - xarray
  - pytorch-gpu
  - pytorch-lightning
  - netcdf4
  - omegaconf
  - wandb
  - optuna
  - joblib
  - cdsapi
